# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table TQUESTION (
  ID                        bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1)  not null,
  QUESTION                  varchar(255),
  CORRECTANSWER             varchar(255),
  WRONGANSWER1              varchar(255),
  WRONGANSWER2              varchar(255),
  constraint pk_TQUESTION primary key (ID))
;




# --- !Downs

SET DATABASE REFERENTIAL INTEGRITY FALSE;

drop table if exists TQUESTION;

SET DATABASE REFERENTIAL INTEGRITY TRUE;

